=== TRIADE-EDUC/TRIADE/triade/pmb/includes/XMLlist.dtd
<!ELEMENT XMLlist (entry+)>
<!ELEMENT entry (#PCDATA)>
<!ATTLIST entry 
	code NMTOKEN #REQUIRED
 	order NMTOKEN #IMPLIED
 	js NMTOKEN #IMPLIED
 	reverse_code NMTOKEN #IMPLIED
 	reverse_code_default_checked NMTOKEN #IMPLIED
 	nature NMTOKEN #IMPLIED
>

=== TRIADE-EDUC/TRIADE/triade/pmb/admin/connecteurs/out/bibloto/messages/en_UK.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE XMLlist SYSTEM "../../../../../includes/XMLlist.dtd" [<!ENTITY nbsp "&amp;nbsp;">]>

<!-- messages localisés en français
****************************************************************************************
© 2002-2007 PMB Services / www.sigb.net pmb@sigb.net et contributeurs (voir www.sigb.net)
****************************************************************************************
$Id: en_UK.xml,v 1.5 2019-02-28 13:11:01 ngantier Exp $ -->

<XMLlist>
<entry code="bibloto_service_endpoint">Address of the webservice</entry>
<entry code="bibloto_service_endpoint_unrecorded">Register the source to have it</entry>
<entry code="bibloto_pmb_ws_url">Url of the source of the loan (owner of the document)</entry>
<entry code="bibloto_style_url">Url of the style of the SelfCheck system</entry>
<entry code="bibloto_checkout_activate">Document loan</entry>
<entry code="bibloto_checkout_activate_yes">Yes</entry>
<entry code="bibloto_checkout_activate_no">No</entry>
<entry code="bibloto_auto_checkout">Enable the loan validation</entry>
<entry code="bibloto_auto_checkout_yes">Yes</entry>
<entry code="bibloto_auto_checkout_no">No</entry>
<entry code="bibloto_checkin_activate">Return of documents</entry>
<entry code="bibloto_checkin_activate_yes">Yes</entry>
<entry code="bibloto_checkin_activate_no">No</entry>
<entry code="bibloto_resa_activate">Show the reservations</entry>
<entry code="bibloto_resa_activate_yes">Yes</entry>
<entry code="bibloto_resa_activate_no">No</entry>
<entry code="bibloto_printer_activate">Printing of the loan ticket</entry>
<entry code="bibloto_printer_activate_yes">Yes</entry>
<entry code="bibloto_printer_activate_no">No</entry>
<entry code="bibloto_printer_name">Name of the printer</entry>
<entry code="bibloto_printer_tpl">Template of the loan ticket</entry>
<entry code="bibloto_sound_activate">Enable the audio alerts</entry>
<entry code="bibloto_sound_activate_yes">yes</entry>
<entry code="bibloto_sound_activate_no">No</entry>
<entry code="bibloto_default_action">Default screen</entry>
<entry code="bibloto_default_action_default">Choice of the action</entry>
<entry code="bibloto_default_action_checkout">Loans screen</entry>
<entry code="bibloto_default_action_checkin">Returns screen</entry>
<entry code="bibloto_default_action_resa">Reservations screen</entry>
<entry code="bibloto_default_action_end">Default screen after a loan or a return</entry>
<entry code="bibloto_default_action_end_default">Choice of the action</entry>
<entry code="bibloto_default_action_end_home">Home screen</entry>
<entry code="bibloto_rfid_activate">Enable the RFID</entry>
<entry code="bibloto_rfid_activate_yes">Yes</entry>
<entry code="bibloto_rfid_activate_no">No</entry>
<entry code="bibloto_rfid_activate_empr">Enable the RFID to read reader cards</entry>
<entry code="bibloto_rfid_activate_empr_yes">Yes</entry>
<entry code="bibloto_rfid_activate_empr_no">No</entry>
<entry code="bibloto_rfid_activate_expl">Enable the RFID to read document tags</entry>
<entry code="bibloto_rfid_activate_expl_yes">Yes</entry>
<entry code="bibloto_rfid_activate_expl_no">No</entry>
<entry code="bibloto_rfid_driver">RFID Driver</entry>
<entry code="bibloto_rfid_library_code">Library code (10 characters)</entry>
<entry code="bibloto_rfid_serveur_url">URL of the RFID server</entry>
<entry code="bibloto_rfid_security_activate">Enable the management of the anti-theft</entry>
<entry code="bibloto_rfid_security_activate_yes">Yes</entry>
<entry code="bibloto_rfid_security_activate_no">No</entry>
<entry code="bibloto_rfid_afi_security_code_on">AFI anti-theft code active</entry>
<entry code="bibloto_rfid_afi_security_code_off">AFI anti-theft code inactive</entry>
<entry code="bibloto_msg_checkout_button">Label of the loan button</entry>
<entry code="bibloto_msg_checkout_button_value">Loan</entry>
<entry code="bibloto_msg_checkin_button">Label of the return button</entry>
<entry code="bibloto_msg_checkin_button_value">Return</entry>
<entry code="bibloto_msg_resa_button">Label of the reservation button</entry>
<entry code="bibloto_msg_resa_button_value">Reservations</entry>
<entry code="bibloto_msg_printer_button">Label of the button to print the loan ticket</entry>
<entry code="bibloto_msg_exit_button">Label of the button to return to the home page</entry>
<entry code="bibloto_msg_exit_button_value">Déconnexion</entry>
<entry code="bibloto_msg_action_title">Label of the list of all the ongoing loans</entry>
<entry code="bibloto_msg_action_title_value">Libellé de la liste de tous les prêts en cours</entry>
<entry code="bibloto_msg_checkout_title">Label of the list of the lent documents</entry>
<entry code="bibloto_msg_checkout_title_value">Prêts effectués</entry>
<entry code="bibloto_msg_checkin_title">Label of the list of the returned documents</entry>
<entry code="bibloto_msg_checkin_title_value">Retours effectués</entry>
<entry code="bibloto_msg_resa_title">Label of the list of the reservations</entry>
<entry code="bibloto_msg_resa_title_value">Réservations</entry>
<entry code="bibloto_msg_dialog_place_item_checkout">Message of the action place a document for the loan</entry>
<entry code="bibloto_msg_dialog_place_item_checkout_value">Poser un document pour effectuer le prêt</entry>
<entry code="bibloto_msg_dialog_place_item_checkin">Message of the action place a document for the return</entry>
<entry code="bibloto_msg_dialog_place_item_checkin_value">Poser un document pour effectuer le retour</entry>
<entry code="bibloto_msg_dialog_too_many_items">Error message too many documents</entry>
<entry code="bibloto_msg_dialog_too_many_items_value">Too many documents !</entry>
<entry code="bibloto_msg_dialog_item_cb_unknown">Error message if unknown document</entry>
<entry code="bibloto_msg_dialog_item_cb_unknown_value">Ce document est inconnu</entry>
<entry code="bibloto_msg_dialog_checkout_possible">Message if copy is available on loan</entry>
<entry code="bibloto_msg_dialog_checkout_possible_value">Empruntable</entry>
<entry code="bibloto_msg_dialog_checkout_ok">Message of loan made</entry>
<entry code="bibloto_msg_dialog_checkout_ok_value">Prêt effectué</entry>
<entry code="bibloto_msg_dialog_checkout_no">Message of loan error</entry>
<entry code="bibloto_msg_dialog_checkout_no_value">Vous ne pouvez pas emprunter ce document !</entry>
<entry code="bibloto_msg_dialog_checkin_ok">Message of document returned</entry>
<entry code="bibloto_msg_dialog_checkin_ok_value">Retour effectué</entry>
<entry code="bibloto_msg_dialog_checkin_no_checkout">Error message in return if the document was not on loan</entry>
<entry code="bibloto_msg_dialog_checkin_no_checkout_value">This document was not on loan</entry>
<entry code="bibloto_msg_dialog_checkin_no">Message of return error</entry>
<entry code="bibloto_msg_dialog_antivol_error">Message of anti-theft error</entry>
<entry code="bibloto_msg_dialog_antivol_error_value">La commande d'antivol n'a pas répondu. Veuillez re-déposer le document !</entry>
<entry code="bibloto_msg_dialog_exit">Label of the Done button</entry>
<entry code="bibloto_timeout_disconnect">Disconnection timeout in seconds</entry>
<entry code="bibloto_home_tpl">Home page template</entry>
<entry code="bibloto_empr_tpl">Borrower record template</entry>
<entry code="bibloto_msg_checkout_valid_button">Label of the loan validation button</entry>
<entry code="bibloto_msg_checkout_valid_button_value">Valider</entry>
<entry code="bibloto_msg_printer_exit_value">Print</entry>
<entry code="bibloto_msg_dialog_exit_value">Exit</entry>
<entry code="bibloto_enable_trombinoscope">Enable employees gallery</entry>
<entry code="bibloto_thumbnail_folder">Borrowers thumbnails URL</entry>
<entry code="bibloto_msg_no_user_found">Message displayed when no user found</entry>
<entry code="bibloto_msg_no_user_found_value">No user found with this search</entry>
<entry code="bibloto_msg_search_title">Message displayed as search title</entry>
<entry code="bibloto_msg_search_title_value">Search for your name to login</entry>
<entry code="pmb_username">Username to authenticate</entry>
<entry code="pmb_password">Password to authenticate</entry>
</XMLlist>

=== TRIADE-EDUC/TRIADE/triade/pmb/external_services/pmbesProcs/messages/en_UK.xml
<?xml version="1.0" encoding="iso-8859-1"?>

<!-- messages localisés en français pour les méthodes externes de procédures
****************************************************************************************
© 2002-2007 PMB Services / www.sigb.net pmb@sigb.net et contributeurs (voir www.sigb.net)
****************************************************************************************
$Id: en_UK.xml,v 1.1 2015-06-15 12:55:35 pmbs Exp $ -->

<!DOCTYPE XMLlist SYSTEM "../../../includes/XMLlist.dtd" >
<XMLlist>
<!-- 
pmbesProcs
-->
  <entry code="Procs_functions_description">Functions related to procedures</entry>
<!-- 
listProcs
-->
  <entry code="listProcs_description">List of procedures</entry>
  <entry code="listProcs_input_description"></entry>
  <entry code="listProcs_result">Return the list</entry>   
<!-- 
executeProc
-->   
  <entry code="executeProc_description">Execution of a procedure</entry>
  <entry code="executeProc_input_description"></entry>
  <entry code="executeProc_procedure">Internal or distant procedure :
  	1 : Internal
  	2 : Distant
  </entry>
  <entry code="executeProc_idProc">Identifier of the procedure</entry>
  <entry code="executeProc_tparams">Table of parameters</entry>
  <entry code="executeProc_result">Result of the execution</entry>  
</XMLlist>

=== TRIADE-EDUC/TRIADE/triade/pmb/cms/modules/tagcloud/messages/fr_FR/cms_module_tagcloud_datasource_tagcloud_records.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE XMLlist SYSTEM "../XMLlist.dtd" [<!ENTITY nbsp "&amp;nbsp;">]>

<!-- messages localisés en français pour le module Article
****************************************************************************************
© 2002-2012 PMB Services / www.sigb.net pmb@sigb.net et contributeurs (voir www.sigb.net)
****************************************************************************************
$Id: cms_module_tagcloud_datasource_tagcloud_records.xml,v 1.3 2014-07-02 07:21:54 ngantier Exp $ -->

<XMLlist>
	<entry code='cms_module_tagcloud_datasource_tagcloud_no_parameters'>Aucun paramètre pour cette source.</entry>
	<entry code='cms_module_tagcloud_datasource_admin_facette'>Nuages</entry>
	<entry code='cms_module_tagcloud_datasource_admin_rmc'>Multi-critères</entry>
	<entry code='cms_module_tagcloud_selector_tagcloud'>Liste de notices</entry>
	<entry code='cms_module_tagcloud_datasource_admin_facette_add'>Ajouter une recherche</entry>
	<entry code='cms_module_tagcloud_datasource_admin_rmc_add'>Ajouter une recherche</entry>
	<entry code='cms_module_tagcloud_datasource_admin_facette_name'>Nom du nuage</entry>
	<entry code='cms_module_tagcloud_datasource_admin_facette_list'>Critère principal</entry>
	<entry code='cms_module_tagcloud_datasource_admin_facette_add'>Ajouter</entry>
	<entry code='cms_module_tagcloud_datasource_admin_critere'>Critères</entry>
	<entry code='cms_module_tagcloud_datasource_admin_ss_critere'>Sous critères</entry>
	<entry code='cms_module_tagcloud_datasource_admin_search_field'>Recherche sur les champs</entry>
	<entry code='cms_module_tagcloud_datasource_admin_search_word'>Recherche sur les mots</entry>
	<entry code='cms_module_tagcloud_datasource_admin_rmc_name'>Nom de la recherche</entry>
	<entry code='cms_module_tagcloud_datasource_admin_rmc_addlabel'>Ajouter un critère de recherche sur</entry>
	<entry code='cms_module_tagcloud_datasource_admin_rmc_add'>Ajouter</entry>
	<entry code='cms_module_tagcloud_datasource_admin_rmc_save'>Enregistrer</entry>
	<entry code='cms_module_tagcloud_datasource_admin_rmc_delete'>Supprimer</entry>
	<entry code='cms_module_tagcloud_datasource_admin_facette_delete'>Supprimer</entry>
	<entry code='cms_module_tagcloud_datasource_admin_rmc_delete_popup'>Etes-vous sur de vouloir supprimer cette recherche ?</entry>
	<entry code='cms_module_tagcloud_datasource_admin_facette_delete_popup'>Etes-vous sur de vouloir supprimer ce nuage ?</entry>
</XMLlist>

=== TRIADE-EDUC/TRIADE/triade/pmb/cms/modules/common/messages/en_UK/cms_module_common_datasource_portfolio.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE XMLlist SYSTEM "../XMLlist.dtd" [<!ENTITY nbsp "&amp;nbsp;">]>

<!-- messages localisés en français pour le module Article
****************************************************************************************
© 2002-2012 PMB Services / www.sigb.net pmb@sigb.net et contributeurs (voir www.sigb.net)
****************************************************************************************
$Id: cms_module_common_datasource_portfolio.xml,v 1.1 2015-06-15 12:55:33 pmbs Exp $ -->

<XMLlist>
	<entry code="cms_module_common_datasource_portfolio_documents">Documents table</entry>
	<entry code="cms_module_common_datasource_portfolio_nb_documents">Number of documents</entry>
	<entry code="cms_module_common_datasource_portfolio_type_object">Type of the related object</entry>
	<entry code="cms_module_common_datasource_portfolio_num_object">Identifier of the related object</entry>
	<entry code="cms_module_common_datasource_list_sort_by_document_create_date">Creation date</entry>
	<entry code="cms_module_common_datasource_list_sort_by_document_filesize">File size</entry>
	<entry code="cms_module_common_datasource_list_sort_by_document_title">Document name</entry>
	<entry code="cms_module_common_datasource_list_sort_by_document_filename">File name</entry>
	<entry code="cms_module_common_datasource_list_sort_by_document_mimetype">Mimetype</entry>
</XMLlist>

=== TRIADE-EDUC/TRIADE/triade/pmb/cms/modules/carousel/messages/en_UK/cms_module_carousel_view_carousel.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE XMLlist SYSTEM "../XMLlist.dtd" [<!ENTITY nbsp "&amp;nbsp;">]>

<!-- messages localisés en français pour le module Article
****************************************************************************************
© 2002-2012 PMB Services / www.sigb.net pmb@sigb.net et contributeurs (voir www.sigb.net)
****************************************************************************************
$Id: cms_module_carousel_view_carousel.xml,v 1.2 2016-09-20 10:25:42 apetithomme Exp $ -->

<XMLlist>
	<entry code='cms_module_carousel_view_carousel_mode'>Display mode</entry>
	<entry code='cms_module_carousel_view_carousel'>Carousel</entry>
	<entry code='cms_module_carousel_view_carousel_mode_horizontal'>Horizontal</entry>
	<entry code='cms_module_carousel_view_carousel_mode_vertical'>Vertical</entry>
	<entry code='cms_module_carousel_view_carousel_mode_fade'>Fade</entry>
	<entry code='cms_module_carousel_view_carousel_speed'>Transition time (in ms)</entry>
	<entry code='cms_module_carousel_view_carousel_pause'>Pause time (in ms)</entry>
	<entry code='cms_module_carousel_view_carousel_display_quantity'>Number of elements per page</entry>
	<entry code='cms_module_carousel_view_carousel_slide_quantity'>Number of elements moved</entry>
	<entry code='cms_module_carousel_view_carousel_autostart'>Automatic start</entry>
	<entry code='cms_module_carousel_view_carousel_autohover'>Pause when hovering</entry>
	<entry code='cms_module_carousel_view_carousel_pager'>Display of the links towards the elements</entry>
	<entry code='cms_module_carousel_view_carousel_yes'>Yes</entry>
	<entry code='cms_module_carousel_view_carousel_no'>No</entry>
	<entry code='cms_module_carousel_manage_default_css'>CSS to apply by default</entry>
	<entry code='cms_module_carousel_view_template_item'>Template of an item</entry>
	<entry code='cms_module_carousel_view_carousel_css'>Linked CSS</entry>
	<entry code='cms_module_carousel_view_carousel_id_desc'>Identifier of the frame</entry>
	<entry code='cms_module_carousel_view_carousel_record_content_desc'>Final appearance of a record template</entry>
	<entry code='cms_module_common_view_django_template_record_content'>Record template to use for the content</entry>
</XMLlist>

=== TRIADE-EDUC/TRIADE/triade/pmb/cms/modules/itemslist/messages/en_UK/cms_module_itemslist_view_django_by_tags.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE XMLlist SYSTEM "../XMLlist.dtd" [<!ENTITY nbsp "&amp;nbsp;">]>

<!-- messages localisés en français pour la classe datasource
****************************************************************************************
© 2002-2012 PMB Services / www.sigb.net pmb@sigb.net et contributeurs (voir www.sigb.net)
****************************************************************************************
$Id: cms_module_itemslist_view_django_by_tags.xml,v 1.1 2015-10-13 07:42:56 dgoron Exp $ -->

<XMLlist>
	<entry code="cms_module_itemslist_view_django_build_item_link">Construction du lien vers un item</entry>
	<entry code="cms_module_itemslist_view_django_by_tags_item_link_desc">Lien vers l'item</entry>
	<entry code="cms_module_itemslist_view_django_build_tag_link">Construction du lien vers un tag</entry>
	<entry code="cms_module_itemslist_view_django_by_tags_tag_link_desc">Lien vers le tag</entry>
	<entry code="cms_module_itemslist_view_django_by_tags_tags_desc">Tableau des tags</entry>
	<entry code="cms_module_itemslist_view_django_by_tags_tags_id_desc">Identifiant du tag</entry>
	<entry code="cms_module_itemslist_view_django_by_tags_tags_label_desc">Libellé du tag</entry>
	<entry code="cms_module_itemslist_view_django_by_tags_tags_items_desc">Tableau des items associés à ce tag</entry>
</XMLlist>

=== TRIADE-EDUC/TRIADE/triade/pmb/cms/modules/common/messages/en_UK/cms_module_common_selector_empr_infos.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE XMLlist SYSTEM "../XMLlist.dtd" [<!ENTITY nbsp "&amp;nbsp;">]>

<!-- messages localisés en français pour le module Article
****************************************************************************************
© 2002-2012 PMB Services / www.sigb.net pmb@sigb.net et contributeurs (voir www.sigb.net)
****************************************************************************************
$Id: cms_module_common_selector_empr_infos.xml,v 1.1 2015-06-15 12:55:33 pmbs Exp $ -->

<XMLlist>	
	<entry code="cms_module_common_selector_empr_infos_val_choice">Field to retrieve</entry>
	<entry code="cms_module_common_selector_empr_infos_statut">Borrower's status</entry>
	<entry code="cms_module_common_selector_empr_infos_categ">Borrower's category</entry>
	<entry code="cms_module_common_selector_empr_infos_codestat">Borrower's statistical code</entry>
	<entry code="cms_module_common_selector_empr_infos_values_choice">Values to retrieve</entry>
	<entry code="cms_module_common_selector_empr_infos_val">Choose a field</entry>
	<entry code="cms_module_common_selector_empr_infos_values">Choose the values</entry>
	<entry code=""></entry>
	<entry code=""></entry>
</XMLlist>

=== TRIADE-EDUC/TRIADE/triade/pmb/classes/frbr/entities/common/messages/fr_FR/frbr_entity_common_datasource_custom_fields.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE XMLlist SYSTEM "../XMLlist.dtd" [<!ENTITY nbsp "&amp;nbsp;">]>

<!-- messages localisés en français pour la classe racine d'un module
****************************************************************************************
© 2002-2012 PMB Services / www.sigb.net pmb@sigb.net et contributeurs (voir www.sigb.net)
****************************************************************************************
$Id: frbr_entity_common_datasource_custom_fields.xml,v 1.1 2018-03-28 09:23:58 dgoron Exp $ -->

<XMLlist>
	<entry code="frbr_entity_records_datasource_custom_fields">Notices</entry>
	<entry code="frbr_entity_authors_datasource_custom_fields">Auteurs</entry>
	<entry code="frbr_entity_categories_datasource_custom_fields">Catégories</entry>
	<entry code="frbr_entity_concepts_datasource_custom_fields">Concepts</entry>
	<entry code="frbr_entity_publishers_datasource_custom_fields">Editeurs</entry>
	<entry code="frbr_entity_collections_datasource_custom_fields">Collections</entry>
	<entry code="frbr_entity_subcollections_datasource_custom_fields">Sous-collection</entry>
	<entry code="frbr_entity_series_datasource_custom_fields">Titres de série</entry>
	<entry code="frbr_entity_works_datasource_custom_fields">Oeuvres</entry>
	<entry code="frbr_entity_indexint_datasource_custom_fields">Indexations décimales</entry>
	<entry code="frbr_entity_authperso_datasource_custom_fields">Autorités personnalisées</entry>
	<entry code="frbr_entity_common_datasource_custom_fields_choice">Choix du champ</entry>
</XMLlist>
