=== TRIADE-EDUC/TRIADE/triade/pmb/includes/XMLlist.dtd
<!ELEMENT XMLlist (entry+)>
<!ELEMENT entry (#PCDATA)>
<!ATTLIST entry 
	code NMTOKEN #REQUIRED
 	order NMTOKEN #IMPLIED
 	js NMTOKEN #IMPLIED
 	reverse_code NMTOKEN #IMPLIED
 	reverse_code_default_checked NMTOKEN #IMPLIED
 	nature NMTOKEN #IMPLIED
>

=== TRIADE-EDUC/TRIADE/triade/pmb/admin/connecteurs/in/lastfm/messages/en_UK.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE XMLlist SYSTEM "../XMLlist.dtd" [<!ENTITY nbsp "&amp;nbsp;">]>

<!-- messages localisés en français pour le connecteur LastFM
****************************************************************************************
© 2002-2007 PMB Services / www.sigb.net pmb@sigb.net et contributeurs (voir www.sigb.net)
****************************************************************************************
$Id: en_UK.xml,v 1.1 2015-06-15 12:55:35 pmbs Exp $ -->

<XMLlist>
	<entry code="lastfm">LastFM</entry>
	<entry code="lastfm_callback_url">URL to fill in in Callback URL when registering on LastFM</entry>
	<entry code="lastfm_api_key">API key</entry>
	<entry code="lastfm_secret_key">Secret key</entry>
	<entry code="lastfm_no_source">First save the source to have the URL!</entry>
	<entry code="lastfm_token">Allow the application on LastFM</entry>
	<entry code="lastfm_link_allow_ws">Click to allow</entry>
	<entry code="lastfm_ws_allow_in_progress">You have to save the source to validate</entry>
	<entry code="lastfm_ws_allowed">Allowed</entry>
	<entry code="lastfm_allow_need_api_key">You have to fill in the keys before asking for the authorization</entry>
	<entry code="lastfm_enrichment_source">(enrichment from Last FM)</entry>
	<entry code="lastfm_see_picture">See the image on LastFM</entry>
	<entry code="lastfm_no_informations">No information in available.</entry>
</XMLlist>

=== TRIADE-EDUC/TRIADE/triade/pmb/external_services/pmbesBackup/messages/en_UK.xml
<?xml version="1.0" encoding="iso-8859-1"?>

<!-- messages localisés en français pour la classe de fonctions search_functions
****************************************************************************************
© 2002-2007 PMB Services / www.sigb.net pmb@sigb.net et contributeurs (voir www.sigb.net)
****************************************************************************************
$Id: en_UK.xml,v 1.1 2015-06-15 12:55:34 pmbs Exp $ -->

<!DOCTYPE XMLlist SYSTEM "../../../includes/XMLlist.dtd" >
<XMLlist>
<!-- 
pmbesBackup
 -->
 <entry code="Backup_functions_description">Backup-related functions</entry>
<!-- 
listGroupsTables
 --> 
  <entry code="listGroupsTables_description">List of table groupments for the backup</entry>
  <entry code="listSauvPerformed_output_description"></entry>
  <entry code="listGroupsTables_result">Returns the list of the groups of tables</entry>   
<!-- 
listTablesUnsaved
 -->  
  <entry code="listTablesUnsaved_description">List of unsaved tables</entry>
  <entry code="listSauvPerformed_output_description"></entry>
  <entry code="listTablesUnsaved_unsavedTables">Returns the list of unsaved tables</entry>  
<!-- 
launchBackup
 -->
  <entry code="launchBackup_description">Launching of a backup set</entry>
  <entry code="launchBackup_input_description"></entry>
  <entry code="launchBackup_id_sauvegarde">Identifier of the backup set</entry>  
  <entry code="listSauvPerformed_output_description"></entry>
  <entry code="launchBackup_result">Return the backup result</entry> 
<!-- 
listSetBackup
 -->
  <entry code="listSetBackup_description">List of the backup sets</entry>
  <entry code="listSetBackup_input_description"></entry>
  <entry code="listSauvPerformed_output_description"></entry>
  <entry code="listSetBackup_result">Returns the list of the backup sets saved</entry>   
 <!-- 
listSauvPerformed
 -->
  <entry code="listSauvPerformed_description">list of backups made</entry>
  <entry code="listSauvPerformed_output_description"></entry>
  <entry code="listSauvPerformed_result">Returns the already made backups</entry>
 <!-- 
deleteSauvPerformed
 -->
  <entry code="deleteSauvPerformed_description">Deletion of a save made</entry>
  <entry code="deleteSauvPerformed_ids_log">Identifiers, separated by a coma ","</entry>
  <entry code="deleteSauvPerformed_output_description"></entry>
  <entry code="deleteSauvPerformed_result">
  	1 :  if the identifiers passed to parameters have been deleted
  	0 :  if an error happened
  </entry>    
</XMLlist>

=== TRIADE-EDUC/TRIADE/triade/pmb/includes/marc_tables/z3950attributes.xml
<?xml version="1.0" encoding="iso-8859-1"?>

<!DOCTYPE XMLlist SYSTEM "../../XMLlist.dtd">

<!-- attributes labels for z3950 servers 
$Id: z3950attributes.xml,v 1.2 2018-05-23 08:57:08 plmrozowski Exp $ -->

<XMLlist>
<entry code="auteur">auteur</entry>
<entry code="isbn">isbn</entry>
<entry code="sujet">sujet</entry>
<entry code="titre">titre</entry>
<entry code="mots">mots</entry>
<entry code="issn">issn</entry>
<entry code="ismn">ismn</entry>
<entry code="isrn">isrn</entry>
<entry code="resume">resume</entry>
<entry code="type_doc">type_doc</entry>
<entry code="cbsonores">cbsonores</entry>
<entry code="ean">ean</entry>
<entry code="notice_id">notice_id</entry>
<entry code="allfields">allfields</entry>
</XMLlist>

=== TRIADE-EDUC/TRIADE/triade/pmb/cms/modules/search/messages/fr_FR/cms_module_search_view_search.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE XMLlist SYSTEM "../XMLlist.dtd" [<!ENTITY nbsp "&amp;nbsp;">]>

<!-- messages localisés en français pour la vue du module de recherche
****************************************************************************************
© 2002-2012 PMB Services / www.sigb.net pmb@sigb.net et contributeurs (voir www.sigb.net)
****************************************************************************************
$Id: cms_module_search_view_search.xml,v 1.9 2018-11-19 10:17:28 ngantier Exp $ -->

<XMLlist>
	<entry code='cms_module_search_button_label'>Rechercher</entry>
	<entry code='cms_module_search_view_help'>Afficher le bouton d'aide</entry>
	<entry code='cms_module_search_view_help_yes'>Oui</entry>
	<entry code='cms_module_search_view_help_no'>Non</entry>
	<entry code='cms_module_search_help'>Aide</entry>
	<entry code='cms_module_search_view_title'>Titre du cadre de recherche</entry>
	<entry code='cms_module_search_view_link_search_advanced'>Afficher le lien de recherche avancée</entry>
	<entry code='cms_module_search_view_link_search_advanced_yes'>Oui</entry>
	<entry code='cms_module_search_view_link_search_advanced_no'>Non</entry>
	<entry code='cms_module_search_view_link_search_advanced_display'>Recherche avancée</entry>
	<entry code='cms_module_search_view_input_placeholder'>Texte indicatif par défaut</entry>
	<entry code='cms_module_search_view_advanced_parameters'>Paramétrage avancé</entry>
	<entry code='cms_module_search_view_others_links'>Autres liens :</entry>
	<entry code='cms_module_search_view_link_url'>Lien :</entry>
	<entry code='cms_module_search_view_link_check'>Vérifier</entry>
	<entry code='cms_module_search_view_link_label'>Libellé :</entry>
	<entry code='cms_module_search_view_link_target'>Ouvrir dans un nouvel onglet</entry>
	<entry code='cms_module_search_view_nofill'>Vider la saisie de recherche après en avoir effectuée une</entry>
</XMLlist>

=== TRIADE-EDUC/TRIADE/triade/pmb/cms/modules/watcheslist/messages/en_UK/cms_module_watcheslist_selector_watches_generic.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE XMLlist SYSTEM "../XMLlist.dtd" [<!ENTITY nbsp "&amp;nbsp;">]>

<!-- messages localisés en français pour le module Article
****************************************************************************************
© 2002-2012 PMB Services / www.sigb.net pmb@sigb.net et contributeurs (voir www.sigb.net)
****************************************************************************************
$Id: cms_module_watcheslist_selector_watches_generic.xml,v 1.1 2015-06-15 12:55:33 pmbs Exp $ -->

<XMLlist>
	<entry code="cms_module_common_selector_sub_choice_label">Selection of watches</entry>
	<entry code="cms_module_watcheslist_selector_watches">Manual selection</entry>
	<entry code="cms_module_common_selector_env_var">Selection through an environment label</entry>
	<entry code="cms_module_common_selector_type_article_generic">Selection a generic field</entry>	
	<entry code="cms_module_common_selector_type_article">Selection trhough a field of an article's content type</entry>	
	<entry code="cms_module_common_selector_type_section_generic">Selection through a generic field of a rubric</entry>	
	<entry code="cms_module_common_selector_type_section">Selection through a field of a rubric's content type</entry>	
	<entry code='cms_module_watcheslist_selector_watches_by_categories'>Selection by sortings</entry>
</XMLlist>

=== TRIADE-EDUC/TRIADE/triade/pmb/cms/modules/metadatas/messages/fr_FR/cms_module_metadatas_datasource_metadatas_record.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE XMLlist SYSTEM "../XMLlist.dtd" [<!ENTITY nbsp "&amp;nbsp;">]>

<!-- messages localisés en français pour le module Article
****************************************************************************************
© 2002-2012 PMB Services / www.sigb.net pmb@sigb.net et contributeurs (voir www.sigb.net)
****************************************************************************************
$Id: cms_module_metadatas_datasource_metadatas_record.xml,v 1.4 2018-01-15 10:06:34 ngantier Exp $ -->

<XMLlist>
	<entry code="cms_module_common_selector_record">Sélecteur manuel d'une notice</entry>
	<entry code="cms_module_common_selector_env_var">Sélecteur depuis une variable d'environnement</entry>
	<entry code="cms_module_common_selector_type_section">Sélecteur par la valeur d'un champ d'un type de contenu de rubrique</entry>
	<entry code="cms_module_common_selector_type_article">Sélecteur par la valeur d'un champ d'un type de contenu d'article</entry>
	<entry code="cms_module_common_selector_type_article_generic">Sélecteur par la valeur d'un champ générique d'article</entry>
	<entry code="cms_module_common_selector_type_section_generic">Sélecteur par la valeur d'un champ générique de rubrique</entry>
	<entry code="cms_module_common_selector_record_permalink">Sélecteur depuis un permalink</entry>

	<entry code='cms_module_metadatas_datasource_metadatas_record_link_desc'>Lien vers la notice</entry>
	<entry code='cms_module_metadatas_datasource_metadatas_record_record_desc'>Description de la notice</entry>
	<entry code="cms_module_metadatas_datasource_main_fields">Champs principaux</entry>
	<entry code="cms_module_metadatas_datasource_record_id_desc">Identifiant de la notice</entry>
	<entry code="cms_module_metadatas_datasource_record_header_desc">En-tête</entry>
	<entry code="cms_module_metadatas_datasource_record_resume_desc">Résumé</entry>
	<entry code="cms_module_metadatas_datasource_record_content_desc">Contenu</entry>
	<entry code="cms_module_metadatas_datasource_record_link_desc">Lien</entry>
	<entry code="cms_module_metadatas_datasource_record_title_desc">Titre</entry>
	<entry code="cms_module_metadatas_datasource_record_vign_desc">Vignette</entry>
	<entry code="cms_module_metadatas_datasource_record_used_template">Choix du template</entry>
	<entry code="cms_module_metadatas_datasource_record_data">Données de la notice</entry>
</XMLlist>

=== TRIADE-EDUC/TRIADE/triade/pmb/admin/connecteurs/out/oai/messages/en_UK.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE XMLlist SYSTEM "../../../../../includes/XMLlist.dtd" [<!ENTITY nbsp "&amp;nbsp;">]>

<!-- messages localisés en français
****************************************************************************************
© 2002-2007 PMB Services / www.sigb.net pmb@sigb.net et contributeurs (voir www.sigb.net)
****************************************************************************************
$Id: en_UK.xml,v 1.4 2016-11-18 09:32:12 jpermanne Exp $ -->

<XMLlist>
	<entry code="illegal_verb">Illegal Verb</entry>
	<entry code="set_none">[None]</entry>
	<entry code="repository_name">Repository name</entry>
	<entry code="admin_email">E-mail address of the admin</entry>
	<entry code="included_sets">Sets included in the source</entry>
	<entry code="repositoryIdentifier">Identifier of the repository</entry>
	<entry code="unconfigured_source">This OAI source is not configured</entry>
	<entry code="cannotDisseminateFormat">%s is not a format supported by this repository</entry>
	<entry code="chunksize">Number of results per query</entry>
	<entry code="token_lifeduration">Life duration of the tokens in seconds</entry>
	<entry code="unknown_set">The specified set does not exist in this repository</entry>
	<entry code="badResumptionToken">The specified token is either expired or invalid</entry>
	<entry code="cache_complete_records">Cache the complete recordings</entry>
	<entry code="cache_complete_records_seconds">Life duration of the recordings in the cache (seconds)</entry>
	<entry code="idDoesNotExist">The requested recording does not exist in this repository</entry>
	<entry code="link_status_to_deletion">Link a record status to the OAI deletion information</entry>
	<entry code="linked_status_to_deletion">Linked status</entry>
	<entry code="noRecordsMatch">No recording found</entry>
	<entry code="allow_gzip_compression">Allow the gzip compression of the queries</entry>
	<entry code="allowed_admin_convert_paths">Additional conversion formats allowed</entry>
	<entry code="builtin_formats">Formats included by default</entry>
	<entry code="baseURL">Base URL of the repository</entry>
	<entry code="baseURL_default">Default address</entry>
	<entry code="baseURL_sourceadd">Register the source to modify this field</entry>
	<entry code="include_items">Keep the informations of the copies in the zone 995</entry>
	<entry code='feuille_xslt'>Customized XSLT sheet for the Dublin Core</entry>
	<entry code='suppr_feuille_xslt'>Delete this sheet</entry>
	<entry code='deletion_management'>Mode de gestion des suppressions des enregistrements</entry>
	<entry code='deletion_management_none'>Aucune</entry>
	<entry code='deletion_management_transient'>Transitoire</entry>
	<entry code='deletion_management_transient_duration'>durée (secondes) :</entry>
	<entry code='deletion_management_persistent'>Persistant</entry>
	<entry code='if_none_status_to_deletion'>(Si aucun statut lié)</entry>
	<entry code="use_items_update_date">Use items update date</entry>
	<entry code="badArgument">Bad Argument</entry>
	<entry code="noSetHierarchy">Set introuvable</entry>
	<entry code="oai_pmh_valid">Validité OAI-PMH</entry>
</XMLlist>

=== TRIADE-EDUC/TRIADE/triade/pmb/admin/acces/empr_docnum/messages/en_UK.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE XMLlist SYSTEM "../XMLlist.dtd" [<!ENTITY nbsp "&amp;nbsp;">]>

<!-- messages localisés en français pour la gestion des droits d'accès Emprunteurs Notices
****************************************************************************************
© 2002-2007 PMB Services / www.sigb.net pmb@sigb.net et contributeurs (voir www.sigb.net)
****************************************************************************************
$Id: en_UK.xml,v 1.4 2015-06-26 08:49:44 pmbs Exp $ -->

<XMLlist>
	<entry code="long_name">Borrowers' access rights - Digital documents</entry>
	<entry code="menu_name">Borrowers - Digital documents</entry>
	<entry code="user_prf_lib">Borrowers roles</entry>
	<entry code="user_prf_bt_add">Add a role</entry>
	<entry code="user_prf_bt_calc">Automatic calculation of the roles</entry>
	<entry code="user_prf_calc_list_lib">Calculated borrowers roles</entry>
	<entry code="user_prf_used_list_lib">Established borrowers roles</entry>
	<entry code="user_prf_unused_list_lib">Previous borrowers roles to reassign</entry>
	<entry code="user_prf_calc_lib">Borrower role</entry>
	<entry code="user_prf_def_lib">Default borrower role (not precised)</entry>
	
	<entry code="res_prf_lib">Digital documents profiles</entry>
	<entry code="res_prf_bt_add">Add a profile</entry>
	<entry code="res_prf_bt_calc">Automatic calculation of the profiles</entry>
	<entry code="res_prf_calc_list_lib">Digital documents profiles calculated</entry>
	<entry code="res_prf_used_list_lib">Digital documents profiles established</entry>
	<entry code="res_prf_unused_list_lib">Previous digital documents profiles to reassign</entry>
	<entry code="res_prf_calc_lib">Digital document profile</entry>
	<entry code="res_prf_def_lib">Default digital document profile (not precised)</entry>
	
	<entry code="dom_mod_rights">Modify the digital document access rights</entry> 
	<entry code="dom_mod_pro">Modify the digital document profile</entry>
	
	<entry code="view_docnum_opac">Reading in viewer</entry>
	<entry code="download_docnum_opac">Download</entry>
	<entry code="show_docnum_opac">Visible in the record</entry>

	<entry code="override">Borrowers access rights overridden - Digital documents</entry>
	<entry code="override_none">Do nothing</entry>
	<entry code="override_yes">Override</entry>
	<entry code="override_no">Delete</entry>
	<entry code="dom_override_rights">Allow the overriding of the access rights in the borrower's record</entry>
</XMLlist>
