=== TRIADE-EDUC/TRIADE/triade/pmb/includes/XMLlist.dtd
<!ELEMENT XMLlist (entry+)>
<!ELEMENT entry (#PCDATA)>
<!ATTLIST entry 
	code NMTOKEN #REQUIRED
 	order NMTOKEN #IMPLIED
 	js NMTOKEN #IMPLIED
 	reverse_code NMTOKEN #IMPLIED
 	reverse_code_default_checked NMTOKEN #IMPLIED
 	nature NMTOKEN #IMPLIED
>

=== TRIADE-EDUC/TRIADE/triade/pmb/external_services/pmbesScanDocnum/messages/en_UK.xml
<?xml version="1.0" encoding="iso-8859-1"?>

<!-- messages localisés en français pour la classe de fonctions pmbesMySQL
****************************************************************************************
© 2002-2007 PMB Services / www.sigb.net pmb@sigb.net et contributeurs (voir www.sigb.net)
****************************************************************************************
$Id: en_UK.xml,v 1.2 2015-06-22 14:42:09 pmbs Exp $ -->

<!DOCTYPE XMLlist SYSTEM "../../../includes/XMLlist.dtd" >
<XMLlist>
<!--
pmbesScanDocnum
-->
  <entry code="ScanDocnum_functions_description">Functions related to the attachment of digital documents</entry>
  <entry code="get_doc_num_description">Reading function and attachment to a digital document</entry>
  <entry code="get_doc_num_upload_repertoire_do_not_exist">The upload directory does not exist</entry>
  <entry code="get_doc_num_rename_error">Error when moving the file</entry>   
  <entry code="get_doc_num_file_not_found">File not found</entry>
  <entry code="get_doc_num_cant_create_explnum">Error creating the digital copy</entry>
  <entry code="get_doc_num_missing_param">There is a missing parameter for the addition of the document</entry>
  <entry code="get_doc_num_missing_link">Digital document with no link to a record or an issue</entry>
</XMLlist>

=== TRIADE-EDUC/TRIADE/triade/pmb/admin/connecteurs/in/databnf/messages/en_UK.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE XMLlist SYSTEM "../XMLlist.dtd" [<!ENTITY nbsp "&amp;nbsp;">]>

<!-- messages localisés en français pour le connecteur OAI
****************************************************************************************
© 2002-2007 PMB Services / www.sigb.net pmb@sigb.net et contributeurs (voir www.sigb.net)
****************************************************************************************
$Id: en_UK.xml,v 1.1 2015-06-15 12:55:34 pmbs Exp $ -->

<XMLlist>
	<entry code="databnf_no_informations">No informations available.</entry>
	<entry code="databnf_enrichment_source">(enrichment from data.bnf.fr)</entry>
	<entry code="databnf_width">Width</entry>
	<entry code="databnf_height">Height</entry>
	<entry code="databnf_label">data.bnf.fr</entry>
	<entry code="databnf_oeuvre_label">The work with data.bnf.fr</entry>
	<entry code="databnf_bio_label">Biography with data.bnf.fr</entry>
	<entry code="databnf_sparql_endpoint_url">URL of the SPARQL access point</entry>
</XMLlist>

=== TRIADE-EDUC/TRIADE/triade/pmb/admin/connecteurs/in/aligastore/messages/en_UK.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE XMLlist SYSTEM "../XMLlist.dtd" [<!ENTITY nbsp "&amp;nbsp;">]>

<!-- messages localisés en français pour le connecteur aligastore
****************************************************************************************
© 2002-2007 PMB Services / www.sigb.net pmb@sigb.net et contributeurs (voir www.sigb.net)
****************************************************************************************
$Id: en_UK.xml,v 1.1 2015-06-15 12:55:35 pmbs Exp $ -->

<XMLlist>
	<entry code="aliga_base_url">Base URL of the aligastore server</entry>
	<entry code="aliga_username">Username</entry>
	<entry code="aliga_password">Password</entry>
	<entry code="aliga_syncbase">Synchronise the entire base</entry>
	<entry code="aliga_sync_noticecaddie">Synchronise the records of a basket of records</entry>
	<entry code="aliga_sync_explcaddie">Synchronise the records of a basket of copies</entry>
	<entry code="aliga_caddie_element">elements</entry>
	<entry code="aliga_fetch_images">Retrieve the images linked to the records</entry>
	<entry code="aliga_image_folder">Folder in which will be stored the images of the records</entry>
	<entry code="aliga_image_folder_public">Public URL of the folder containing the images of the records</entry>
	<entry code="aliga_image_thumburl">URL of the thumbnail</entry>
	<entry code="aliga_image_front">URL of the Recto</entry>
	<entry code="aliga_image_back">URL of the Verso</entry>
	<entry code="aliga_cover_front">Recto</entry>
	<entry code="aliga_cover_back">Verso</entry>
	<entry code="aliga_enrichment_source">(enrichment from Aligastore)</entry>
	<entry code="aliga_enrichment_no_resume">No recap available.</entry>
	<entry code="aliga_enrichment_no_bio">No biography available.</entry>
	<entry code="aliga_enrichment_no_sommaire">No table of contents available</entry>
</XMLlist>

=== TRIADE-EDUC/TRIADE/triade/pmb/admin/connecteurs/out/webdav/messages/fr_FR.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE XMLlist SYSTEM "../../../../../includes/XMLlist.dtd" [<!ENTITY nbsp "&amp;nbsp;">]>

	<!--
		messages localisés en français
		****************************************************************************************
		© 2002-2007 PMB Services / www.sigb.net pmb@sigb.net et contributeurs
		(voir www.sigb.net)
		****************************************************************************************
		$Id: fr_FR.xml,v 1.12 2016-03-31 08:55:44 dgoron Exp $
	-->

<XMLlist>
	<entry code="webdav_restricted_sets">Restreindre à un ou plusieurs sets</entry>
	<entry code="webdav_user_thesaurus">Thésaurus à utiliser pour la navigation</entry>
	<entry code="webdav_only_with_notices">Afficher seulement les catégories qui contiennent des notices concernées</entry>
	<entry code="webdav_yes">Oui</entry>
	<entry code="webdav_no">Non</entry>
	<entry code="webdav_tree">Contruction de l'arborescence</entry>
	<entry code="webdav_authentication">Authentification</entry>
	<entry code="webdav_write_permission">Autoriser l'ajout/modification de documents</entry>
	<entry code="webdav_authenticate_gest">Coté Gestion</entry>
	<entry code="webdav_authenticate_opac">Coté OPAC</entry>
	<entry code="webdav_anonymous">Accès Anonyme</entry>
	<entry code="webdav_restricted_write_permission">Restreindre l'autorisation à certains groupes/catégories d'utilisateurs/lecteurs :</entry>
	<entry code="webdav_restricted_empr_write_permission">Catégories de lecteurs</entry>
	<entry code="webdav_restricted_user_write_permission">Groupes d'utilisateur</entry>
	<entry code="webdav_default_statut">Statut par défaut lors de la création d'une notice</entry>
	<entry code="webdav_base_uri">URI de base du serveur Webdav</entry>
	<entry code="webdav_allow_web">Autoriser l'interface web</entry>
	<entry code="webdav_default_docnum_statut">Statut par défaut du document numérique à sa création</entry>
	<entry code="webdav_select_tree_elem">Sélectionnez un élément</entry>
	<entry code="webdav_metasMapper_class">Choix de la classe pour le traitement des metas données</entry>
	<entry code="webdav_collections_group_tree">Type de collections dans l'arborescence</entry>
	<entry code="webdav_collections_group_standard">Standard</entry>
	<entry code="webdav_collections_group_scan_request">Demande de numérisation</entry>
	<entry code="webdav_collection_typdoc">Type de document</entry>
	<entry code="webdav_collection_status">Statut</entry>
	<entry code="webdav_collection_categorie">Catégorie</entry>
	<entry code="webdav_collection_indexint">Indexation décimale</entry>
	<entry code="webdav_collection_liste_lecture">Liste de lecture</entry>
	<entry code="webdav_collection_liste_lecture_tag">Listes de lecture classées</entry>
	<entry code="webdav_collection_priority">Priorité</entry>
	<entry code="webdav_collection_music">Musique</entry>
	<entry code="webdav_collection_music_concept_before">Concept à associer aux partitions avant exécution</entry>
	<entry code="webdav_collection_music_concept_after">Concept à associer aux partitions après exécution</entry>
	<entry code="webdav_collection_music_concept_blank">Concept à associer aux partitions originales</entry>
</XMLlist>

=== TRIADE-EDUC/TRIADE/triade/pmb/cms/modules/agenda/messages/en_UK/cms_module_agenda_datasource_agenda.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE XMLlist SYSTEM "../XMLlist.dtd" [<!ENTITY nbsp "&amp;nbsp;">]>

<!-- messages localisés en français pour le module Article
****************************************************************************************
© 2002-2012 PMB Services / www.sigb.net pmb@sigb.net et contributeurs (voir www.sigb.net)
****************************************************************************************
$Id: cms_module_agenda_datasource_agenda.xml,v 1.2 2016-09-20 10:25:41 apetithomme Exp $ -->

<XMLlist>
	<entry code="cms_module_common_selector_env_var">Event from an environment variable</entry>
	<entry code="cms_module_agenda_selector_calendars">Calendars created in the administration interface</entry>
	<entry code="cms_module_agenda_selector_calendars_date">Calendars created in the administration interface / Date</entry>
	<entry code="cms_module_agenda_datasource_agenda_event_start_desc">Beginning date</entry>
	<entry code="cms_module_agenda_datasource_agenda_event_start_format_value_desc">Formatted value of the beginning date</entry>
	<entry code="cms_module_agenda_datasource_agenda_event_start_value_desc">Gross value of the beginning date</entry>
	<entry code="cms_module_agenda_datasource_agenda_event_start_time_desc">Timestamp of the beginning date</entry>
	<entry code="cms_module_agenda_datasource_agenda_event_end_desc">End date (optional)</entry>
	<entry code="cms_module_agenda_datasource_agenda_event_end_format_value_desc">Formatted value of the end date</entry>
	<entry code="cms_module_agenda_datasource_agenda_event_end_value_desc">Gross value of the end date</entry>
	<entry code="cms_module_agenda_datasource_agenda_event_end_time_desc">Timestamp of the end date</entry>
	<entry code="cms_module_agenda_datasource_agenda_id_type_desc">Identifier of the content type used for the event</entry>
	<entry code="cms_module_agenda_datasource_agenda_color_desc">Colour of the linked calendar</entry>
	<entry code="cms_module_agenda_datasource_agenda_calendar_desc">Name of the linked calendar</entry>
	<entry code="cms_module_agenda_datasource_agenda_events_desc">Table of events</entry>
</XMLlist>

=== TRIADE-EDUC/TRIADE/triade/pmb/external_services/pmbesSync/messages/en_UK.xml
<?xml version="1.0" encoding="iso-8859-1"?>

<!-- messages localisés en français pour les différentes méthodes
****************************************************************************************
© 2002-2007 PMB Services / www.sigb.net pmb@sigb.net et contributeurs (voir www.sigb.net)
****************************************************************************************
$Id: en_UK.xml,v 1.5 2018-09-20 13:14:23 dgoron Exp $ -->

<!DOCTYPE XMLlist SYSTEM "../../../includes/XMLlist.dtd" >
<XMLlist>
<!-- 
pmbesSync
 -->
  <entry code="Sync_functions_description">Functions related to the repositories</entry>
<!-- 
listEntrepotSources
 --> 
  <entry code="listEntrepotSources_description">List of the source connectors which are repositories</entry>
  <entry code="listEntrepotSources_output_description"></entry>
  <entry code="listEntrepotSources_result">List of the repositories</entry>
<!-- 
doSync
 -->  
  <entry code="doSync_description">Beginning of the synchronization</entry>
  <entry code="doSync_input_description">The optional inputs are necessary for the PMB scheduler</entry>
  <entry code="doSync_id_connector">Identifier of the source connector</entry> 
  <entry code="doSync_id_source">Identifier of the repository source</entry>
  <entry code="doSync_auto_import">Boolean to ask for the automatic import</entry>
  <entry code="doSync_id_tache">Identifier of the task (Optional)</entry>
  <entry code="doSync_callback_listen">Callback function when taking the order (Optional)</entry>
  <entry code="doSync_callback_command">Callback function when processing the order (Optional)</entry>
  <entry code="doSync_output_description"></entry>
  <entry code="doSync_result">Returns the report of the synchronisation</entry> 
  <entry code="doSync_auto_delete">Suppression automatique des notices supprimées du serveur</entry>
  <entry code="doSync_not_in_notices_externes">Ne pas inscrire les notices importées dans la table notices_externes</entry>
  <entry code="doSync_date_start">Date de début (Facultatif)</entry>
  <entry code="doSync_date_end">Date de fin (Facultatif)</entry>  
  <!-- 
emptySource
 -->  
  <entry code="emptySource_description">Vide l'entrepôt</entry>
  <entry code="emptySource_input_description"></entry>
  <entry code="emptySource_id_connector">Identifiant du connecteur de la source</entry>
  <entry code="emptySource_id_source">Identifiant de la source de l'entrepôt</entry>
  <entry code="emptySource_output_description"></entry>
  <entry code="emptySource_result"></entry>
</XMLlist>

=== TRIADE-EDUC/TRIADE/triade/pmb/cms/modules/common/messages/en_UK/cms_module_common_datasource_list.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE XMLlist SYSTEM "../XMLlist.dtd" [<!ENTITY nbsp "&amp;nbsp;">]>

<!-- messages localisés en français pour le module Article
****************************************************************************************
© 2002-2012 PMB Services / www.sigb.net pmb@sigb.net et contributeurs (voir www.sigb.net)
****************************************************************************************
$Id: cms_module_common_datasource_list.xml,v 1.4 2018-05-25 12:05:27 dgoron Exp $ -->

<XMLlist>
	<entry code="cms_module_common_datasource_list_limit">Maximum number of elements to return</entry>
	<entry code="cms_module_common_datasource_list_sort_order">Sort order</entry>
	<entry code="cms_module_common_datasource_list_sort_order_asc">Ascending</entry>
	<entry code="cms_module_common_datasource_list_sort_order_desc">Descending</entry>
	<entry code="cms_module_common_datasource_list_sort_by">Sort by</entry>
	<entry code="cms_module_common_datasource_list_sort_by_publication_date">Publication date</entry>
	<entry code="cms_module_common_datasource_list_sort_by_id_article">Identifier</entry>
	<entry code="cms_module_common_datasource_list_sort_by_article_title">Title</entry>
	<entry code="cms_module_common_datasource_list_sort_by_pert">Pertinence</entry>
	<entry code="cms_module_common_datasource_list_sort_by_section_start_date">Publication date</entry>
	<entry code="cms_module_common_datasource_list_sort_by_id_section">Identifier</entry>
	<entry code="cms_module_common_datasource_list_sort_by_section_title">Title</entry>	
	<entry code="cms_module_common_datasource_list_sort_by_section_order">Position in the editorial content tree</entry>
	<entry code="cms_module_common_datasource_list_sort_by_article_order">Position in the editorial content tree</entry>
	<entry code="cms_module_common_datasource_list_sort_by_item_publication_date">Publication date</entry>
	<entry code="cms_module_common_datasource_list_sort_by_id_item">Identifier</entry>
	<entry code="cms_module_common_datasource_list_sort_by_item_title">Title</entry>
	<entry code="cms_module_common_datasource_list_sort_by_watch_last_date">Date of the last synchronization</entry>
	<entry code="cms_module_common_datasource_list_sort_by_id_watch">Identifier</entry>
	<entry code="cms_module_common_datasource_list_sort_by_watch_title">Title</entry>
	<entry code="cms_module_common_datasource_list_sort_by_id_authority">Identifiant</entry>
	<entry code="cms_module_common_datasource_list_sort_by_date_parution">Date de parution</entry>
	<entry code="cms_module_common_datasource_list_sort_by_notice_id">Identifiant</entry>
	<entry code="cms_module_common_datasource_list_sort_by_index_sew">Titre</entry>
	<entry code="cms_module_common_datasource_list_sort_by_default">Défaut</entry>
	<entry code="cms_module_common_datasource_list_sort_by_name">Libellé</entry>
	<entry code="cms_module_common_datasource_list_sort_by_idetagere">Identifiant</entry>
</XMLlist>

=== TRIADE-EDUC/TRIADE/triade/pmb/cms/modules/tagcloud/messages/en_UK/cms_module_tagcloud_datasource_tagcloud_records.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE XMLlist SYSTEM "../XMLlist.dtd" [<!ENTITY nbsp "&amp;nbsp;">]>

<!-- messages localisés en français pour le module Article
****************************************************************************************
© 2002-2012 PMB Services / www.sigb.net pmb@sigb.net et contributeurs (voir www.sigb.net)
****************************************************************************************
$Id: cms_module_tagcloud_datasource_tagcloud_records.xml,v 1.2 2015-06-16 09:24:41 pmbs Exp $ -->

<XMLlist>
	<entry code='cms_module_tagcloud_datasource_tagcloud_no_parameters'>No parameter found for this source.</entry>
	<entry code='cms_module_tagcloud_datasource_admin_facette'>Clouds</entry>
	<entry code='cms_module_tagcloud_datasource_admin_rmc'>Multi-standards</entry>
	<entry code='cms_module_tagcloud_selector_tagcloud'>Records list</entry>
	<entry code='cms_module_tagcloud_datasource_admin_facette_add'>Add a search</entry>
	<entry code='cms_module_tagcloud_datasource_admin_rmc_add'>Add a search</entry>
	<entry code='cms_module_tagcloud_datasource_admin_facette_name'>Cloud name</entry>
	<entry code='cms_module_tagcloud_datasource_admin_facette_list'>Main standard</entry>
	<entry code='cms_module_tagcloud_datasource_admin_facette_add'>Add</entry>
	<entry code='cms_module_tagcloud_datasource_admin_critere'>Standards</entry>
	<entry code='cms_module_tagcloud_datasource_admin_ss_critere'>Sub-standard(s)</entry>
	<entry code='cms_module_tagcloud_datasource_admin_search_field'>Search on fields</entry>
	<entry code='cms_module_tagcloud_datasource_admin_search_word'>Search on words</entry>
	<entry code='cms_module_tagcloud_datasource_admin_rmc_name'>Search name</entry>
	<entry code='cms_module_tagcloud_datasource_admin_rmc_addlabel'>Add a search standard on</entry>
	<entry code='cms_module_tagcloud_datasource_admin_rmc_add'>Add</entry>
	<entry code='cms_module_tagcloud_datasource_admin_rmc_save'>Save</entry>
	<entry code='cms_module_tagcloud_datasource_admin_rmc_delete'>Delete</entry>
	<entry code='cms_module_tagcloud_datasource_admin_facette_delete'>Delete</entry>
	<entry code='cms_module_tagcloud_datasource_admin_rmc_delete_popup'>Are you sure you want to delete this search ?</entry>
	<entry code='cms_module_tagcloud_datasource_admin_facette_delete_popup'>Are you sure you want to delete this cloud ?</entry>
</XMLlist>
